### ISSUE TITLE
domain name inconsistency for amavisd-new

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [kvaps/kolab-docker#13]
My emails contain the following line in the email header:
`X-Virus-Scanned: amavisd-new at example.com`

I did not use the domain name example.com for the configuration. In contrast the dkim and the sender mail header fields contain the correct domain name. So it seems that the amavisd-new configuration is not aware of the used domain name.

This occurs with the kvaps/docker-kolab standalone version without extra rmilter, clamd and rspamd container.

Does anyone see the same behavior?

**Comment by kvaps** [comment]
Yes, you can change it here: /etc/amavisd/amavisd.conf

``` bash
$mydomain = 'example.com';   # a convenient default for other settings
```

I will fix it later...

**Comment by cguentherTUChemnitz** [comment]
Thanks for your quick response. That indeed fixed the behaviour.
