### ISSUE TITLE
v16 ? 

### ISSUE THREAD

**Issue by rgarrigue** [kvaps/kolab-docker#17]
Hi @kvaps 

Do you plan on updating to kolab v16 ?

Regards,

**Comment by kvaps** [comment]
Yes, currently now I am on vacantion. I will work on this some time later. 
New release will be include many enchancements:
Separated init scripts, docker images and more optimisations.

**Comment by cguentherTUChemnitz** [comment]
@kvaps: Have a nice vacation.

Does anybody know something about the semi official kolab dockerhub images? https://hub.docker.com/u/kolab/

It seems that there exists a lot of small docker images. I guess those images are used for the kolab internal continous integreation pipeline. I think the most sustainable solution would be to use official containers released by the kolab dev team. But the lack of the description and no link to source is like blackbox testing of foreign software. Is it planned by the kolab dev team to provide official docker images for productive use in future? If those linked containers are destinated for that, where we find descriptions and setup tutorials?

best,
Christian

**Comment by rgarrigue** [comment]
I thinks those are related with [this article](https://kanarip.wordpress.com/2015/12/04/the-evolution-of-kolab-development/)
point 5. Not sure though.

2016-04-22 16:33 GMT+02:00 cguentherTUChemnitz notifications@github.com:

**Comment by cguentherTUChemnitz** [comment]
Thanks for the link. It describes pretty much what i expected.

The usage of those kolab provided docker containers are documented in hopfully not too far future.
https://docs.kolab.org/contributor-guide/docker-containers.html
https://git.kolab.org/T1116

I think it would be suitable to wait for this documentation. Maybe it is possible to use those kolab provided docker containers for an up to date preconfigured kolab docker system.

**Comment by Sohalt** [comment]
Any news on this? And will it be easily possible to upgrade to the newer version if I set up the old/current one now?

**Comment by kvaps** [comment]
So far in the development stage, it may be slow, sorry, this is due my heavy workload.

The image is created from scratch and it will be much better than first image.
At the moment, I developed the [baseimage](https://github.com/kvaps/docker-baseimage/tree/systemd) from which new kolab image will be created.
It is Centos7 based and uses systemd.
More details can be found in [v16-dev](https://github.com/kvaps/docker-kolab/tree/v16-dev) branch, but the work is still in full swing, so it is not working for now.

Upgrade from Kolab 4.4 will be provided automaticaly right in the new image, or I will write detailed guide.

Thanks for interesting!

**Comment by Sohalt** [comment]
Thanks a lot for the info! 4.4 should be 3.4 shouldn't it? So it would be safe to use the current image and upgrade, keeping all users, settings and data(?) Can you already give a rough estimate when you will have the new image finished (I know that such estimates are pretty much impossible, but I though I'd ask anyways)?

**Comment by kvaps** [comment]
Yes, sure 3.4 :)
I planed to finish it during 2-3 weeks. perhaps sooner, perhaps later...

**Comment by kvaps** [comment]
Job is done. I released kolab 16 in docker:  https://github.com/kvaps/docker-kolab/tree/v16-beta
New image is systemd based. Update from 3.4 is automatic, but it is not yet tested. Please backup before upgrade!!
Thanks all who will help with testing.

**Comment by danbo** [comment]
v16 readme quick start command begins like this:

docker run \
    **--restart: on-failure:1 \**
    --name kolab \
    ...

it should be

docker run \
    **--restart=on-failure:1 \**
    --name kolab \
    ...

**Comment by kvaps** [comment]
fixed, thanks
