### ISSUE TITLE
ldap_admin_pass shouldn't be mandatory

### ISSUE THREAD

**Issue by rgarrigue** [kvaps/kolab-docker#5]
Hi again

I wanted to leave all the password up to random generation while picking them in the docker after getting it up. But docker logs underline this error

```
err:  Enviroment vaiable $LDAP_ADMIN_PASS is not set.
```

It shouldn't be mandatory since afair setup-kolab will generate it if missing.

**Comment by rgarrigue** [comment]
Actually, I had to specify every single _PASS env variable. Kinda weird, last week I had mysql's commented for sure...

**Comment by kvaps** [comment]
Hi, this feature removed in 287c381.
I think that it may be useful to return back soon.

**Comment by rgarrigue** [comment]
I agree !

2016-01-23 0:36 GMT+01:00 kvaps notifications@github.com:

**Comment by kvaps** [comment]
On the other hand, if you look into the more official docker images like MySQL or Postgres, anywhere you need to set the passwords in the environment variables manually on run.
I suspect that this need for taking passwords from container of this image to linked containers.
I want to follow docker ideologues, and probably I will not release this feature. Sorry.

But I can offer you an alternative way. You may change passwords using sed and pwgen externally. Simple script like:

``` bash
while read i; do echo "$i" | sed "s/<password>/`pwgen -1 16`/" ; done < docker-compose.yml
```

Or without pwgen:

``` bash
while read i; do echo "$i" | sed "s/<password>/`cat /dev/urandom | env LC_CTYPE=C tr -dc a-zA-Z0-9 | head -c 16`/" ; done < docker-compose.yml
```

What do you think about it?

**Comment by kvaps** [comment]
OK, I hope my solution has solved this issue.
