### ISSUE TITLE
master branch ssl folder permissions incorrect - prevents nginx from starting

### ISSUE THREAD

**Issue by danbo** [kvaps/kolab-docker#7]
I'm not sure how I can easily modify the startup script without recompiling the image.. 

info:  start linking default lib and log folders to /data volume
info:  finished linking default lib and log folders to /data volume
warn:  nginx already configured, skipping...
info:  start configuring spam sieve
info:  finished configuring amavis
warn:  no certificates found in /etc/pki/tls/kolab fallback to /etc/pki/tls/kolab
info:  start generating certificate
Generating a 4096 bit RSA private key
............................................................................................................................................................................................................................................++
....++
writing new private key to '/etc/pki/tls/kolab/_/privkey.pem'
/etc/pki/tls/kolab/_/privkey.pem: No such file or directory
140158056220488:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('/etc/pki/tls/kolab/_/privkey.pem','w')
140158056220488:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
touch: cannot touch `/etc/pki/tls/kolab/_/chain.pem': No such file or directory
/bin/start.sh: line 312: /etc/pki/tls/kolab/_/fullchain.pem: No such file or directory
info:  generating certificate finished
chmod: cannot access `/etc/pki/tls/kolab/_/*': No such file or directory

**Comment by kvaps** [comment]
Thanks for your report. Fixed.

> I'm not sure how I can easily modify the startup script without recompiling the image..

You can bring it out of image:

``` bash
-v ./start.sh:/bin/start.sh
```
