### ISSUE TITLE
Sending an email to self results in SMTP Error (454): Authentication Failed

### ISSUE THREAD

**Issue by danbo** [kvaps/kolab-docker#8]
maillog shows:  
postfix/submission/smtpd[2529]: cannot load Certificate Authority data: disabling TLS support.

my chain.pem is empty

Looking at start.sh 
315: cat $certificate_path > $fullchain_path

When I copied my cert.pem to chain.pem, it started working.

**Comment by danbo** [comment]
maillog is however is also still showing 

starttls: TLSv1 with cipher ECDHE-RSA-AES256-SHA (256/256 bits new) no authentication

even though it works, not sure if I should be concerned.

**Comment by danbo** [comment]
maillog is also showing

amavis[938]: (00938-01) (!)connect to /var/spool/amavisd/clamd.sock failed, attempt #1: Can't connect to a UNIX socket /var/spool/amavisd/clamd.sock: 111
amavis[938]: (00938-01) (!)connect to /var/spool/amavisd/clamd.sock failed, attempt #1: Can't connect to a UNIX socket /var/spool/amavisd/clamd.sock: Connection refused

**Comment by kvaps** [comment]
Fixed, thanks for your reports!
